#!/bin/sh -x
# It will run with two args: buildroot spec
BUILDROOT="$1"
SPEC="$2"

PRODUCT=lycheeslicer
PRODUCTDIR=/opt/LycheeSlicer

. $(dirname $0)/common.sh

# Lychee bundles old Qt5/ICU libraries; autogenerated libicu56 requires break
# Fedora while the application uses its bundled libraries.
stop_libs_requires

add_bin_link_command

fix_desktop_file

add_electron_deps
